# Banco
quarkus.datasource.db-kind=postgresql
quarkus.datasource.jdbc.url=jdbc:postgresql://localhost:5432/supercoin
quarkus.datasource.username=postgres
quarkus.datasource.password=Sql2026

# Hibernate (forma atual)
quarkus.hibernate-orm.schema-management.strategy=update
quarkus.hibernate-orm.sql-load-script=import.sql
quarkus.hibernate-orm.log.sql=true

# Dev Services off
quarkus.devservices.enabled=false

mp.jwt.verify.issuer=https://acme.org
quarkus.smallrye-jwt.enabled=true
